-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Profiles (Public User Data)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    role TEXT CHECK (role IN ('customer', 'staff', 'manager')) DEFAULT 'customer',
    full_name TEXT,
    phone_number TEXT,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Policies for Profiles
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 2. Categories
CREATE TABLE public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    image_url TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Categories are viewable by everyone" ON public.categories FOR SELECT USING (true);
CREATE POLICY "Only managers can insert categories" ON public.categories FOR INSERT WITH CHECK (exists (select 1 from public.profiles where id = auth.uid() and role = 'manager'));
CREATE POLICY "Only managers can update categories" ON public.categories FOR UPDATE USING (exists (select 1 from public.profiles where id = auth.uid() and role = 'manager'));

-- 3. Menu Items
CREATE TABLE public.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES public.categories(id),
    name TEXT NOT NULL,
    description TEXT,
    price DECIMAL(10,2) NOT NULL,
    image_url TEXT,
    is_available BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Menu items are viewable by everyone" ON public.menu_items FOR SELECT USING (true);
CREATE POLICY "Only managers can modify menu items" ON public.menu_items FOR ALL USING (exists (select 1 from public.profiles where id = auth.uid() and role = 'manager'));

-- 4. Tables
CREATE TABLE public.tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_number TEXT NOT NULL UNIQUE,
    qr_code_url TEXT,
    status TEXT CHECK (status IN ('free', 'occupied')) DEFAULT 'free',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.tables ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tables are viewable by everyone" ON public.tables FOR SELECT USING (true);
CREATE POLICY "Staff and Managers can update tables" ON public.tables FOR UPDATE USING (exists (select 1 from public.profiles where id = auth.uid() and role IN ('staff', 'manager')));

-- 5. Orders
CREATE TABLE public.orders (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    table_id BIGINT REFERENCES public.tables(id),
    total_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    status TEXT CHECK (status IN ('pending', 'confirmed', 'preparing', 'served', 'cancelled', 'paid')) DEFAULT 'pending',
    payment_status TEXT CHECK (payment_status IN ('unpaid', 'paid')) DEFAULT 'unpaid',
    idempotency_key UUID UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can see their own orders" ON public.orders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Staff/Managers can see all orders" ON public.orders FOR SELECT USING (exists (select 1 from public.profiles where id = auth.uid() and role IN ('staff', 'manager')));
CREATE POLICY "Users can create orders" ON public.orders FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Staff/Manager can update orders" ON public.orders FOR UPDATE USING (exists (select 1 from public.profiles where id = auth.uid() and role IN ('staff', 'manager')));

-- 6. Order Items
CREATE TABLE public.order_items (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    order_id UUID REFERENCES public.orders(id) ON DELETE CASCADE,
    menu_item_id BIGINT REFERENCES public.menu_items(id),
    quantity INTEGER NOT NULL DEFAULT 1,
    price_at_time DECIMAL(10,2) NOT NULL, -- Snapshot price
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can see own order items" ON public.order_items FOR SELECT USING (exists (select 1 from public.orders where id = order_items.order_id and user_id = auth.uid()));
CREATE POLICY "Staff/Manager see all order items" ON public.order_items FOR SELECT USING (exists (select 1 from public.profiles where id = auth.uid() and role IN ('staff', 'manager')));
CREATE POLICY "Users can insert order items" ON public.order_items FOR INSERT WITH CHECK (
    exists (select 1 from public.orders where id = order_id and user_id = auth.uid())
);

-- 7. Idempotency Keys (For Backend Pattern)
CREATE TABLE public.idempotency_keys (
    key UUID PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    response_payload JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.idempotency_keys ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view own keys" ON public.idempotency_keys FOR SELECT USING (auth.uid() = user_id);

-- TRIGGER: Handle New User -> Create Profile
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', 'customer');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Indexes for performance
CREATE INDEX idx_orders_user_id ON public.orders(user_id);
CREATE INDEX idx_orders_status ON public.orders(status);
CREATE INDEX idx_menu_category ON public.menu_items(category_id);
